config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
   sessions: "admins/sessions"
  }

  devise_scope :admin do
    get "dashboard", to: "dashboard#index"
    get "dashboard/login", to: "admins/sessions#new"
    post "dashboard/login", to: "admins/sessions#create"
    delete "dashboard/logout", to: "admins/sessions#destroy"
  end
  namespace :dashboard do
    resources :posts
    resources :menus, except: [:show]
  end
  
  root to: "home#index"
  resources :posts, only: %i[index show]
  resources :contacts, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard/menus_controller.rb
class Dashboard::MenusController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_menu, only: %i[edit update destroy]
  
  def index
    @menus = Menu.all.order(id: "DESC")
  end
  
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to dashboard_menus_path, notice: 'menu was successfully created.'
    else
      render :new, notice: 'Save error.'
    end
  end
  
  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to dashboard_menus_path, notice: 'menu was successfully updated.'
    end
  end

  def destroy
    @menu.destroy
    redirect_to dashboard_menus_url, notice: 'menu was successfully destroyed.'
  end
  
   private
    def set_menu
      @menu = Menu.find(params[:id])
    end
    
    def menu_params
      params.require(:menu).permit(:name, :price, :description, :kcal, :image)
    end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_post, only: %i[show edit update destroy]
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def show
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to dashboard_posts_path, notice: 'Posts was successfully created.'
    end
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_posts_path, notice: 'Post was successfully updated.'
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_posts_url, notice: 'Post was successfully destroyed.'
  end
  
   private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  def index
  end
end

app/helpers/dashboard/menus_helper.rb
module Dashboard::MenusHelper
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag "/images/logo.svg", class: "logo", alt: "WCBカフェ ホーム" %>
  <% end %>
  
  <div id = "menu-bar" class = "fas fa-bars"></div>
  <nav class="navbar">
    <%= link_to 'サイトへ', root_path %>
    <%= link_to '管理サイトトップ', dashboard_path %>
    <%= link_to '記事作成', dashboard_posts_path %>
    <%= link_to '商品作成', dashboard_menus_path %>
    <%= link_to '工事中〜', "#工事中〜" %>
  </nav>
    
</header>

app/views/layouts/dashboard/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name = 'viewport' content = 'width=device-width, initial-scale=1'>
    <title>WCB CAFE</title>
    <meta name = 'description' content = 'ブレンドコーヒートヘルシーなオーガニックフードを提供するカフェ'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://kit.fontawesome.com/8c770f7830.js' crossorigin='anonymous'></script>
  </head>

  <body>
    <%= render partial: 'layouts/dashboard/header' %>

    <%= yield %>
  </body>
</html>