config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
   sessions: "admins/sessions"
  }

  devise_scope :admin do
    get "dashboard", to: "dashboard#index"
    get "dashboard/login", to: "admins/sessions#new"
    post "dashboard/login", to: "admins/sessions#create"
    delete "dashboard/logout", to: "admins/sessions#destroy"
  end
  namespace :dashboard do
    resources :posts
    resources :menus, except: [:show]
  end
  
  root to: "home#index"
  resources :posts, only: %i[index show]
  resources :contacts, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/dashboard/menus_controller.rb
class Dashboard::MenusController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_menu, only: %i[edit update destroy]
  
  def index
    @menus = Menu.all.order(id: "DESC")
  end
  
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to dashboard_menus_path, notice: 'menu was successfully created.'
    else
      render :new, notice: 'Save error.'
    end
  end
  
  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to dashboard_menus_path, notice: 'menu was successfully updated.'
    end
  end

  def destroy
    @menu.destroy
    redirect_to dashboard_menus_url, notice: 'menu was successfully destroyed.'
  end
  
   private
    def set_menu
      @menu = Menu.find(params[:id])
    end
    
    def menu_params
      params.require(:menu).permit(:name, :price, :description, :kcal, :image)
    end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_post, only: %i[show edit update destroy]
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def show
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to dashboard_posts_path, notice: 'Posts was successfully created.'
    end
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_posts_path, notice: 'Post was successfully updated.'
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_posts_url, notice: 'Post was successfully destroyed.'
  end
  
   private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  def index
  end
end

app/helpers/dashboard/menus_helper.rb
module Dashboard::MenusHelper
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/dashboard/menus/_form.html.erb
<%= form_with model: menu, url: url, local: true do |f| %>
  
  <div class="">
    <%= f.text_field :name, label: "商品名", placeholder: "20文字以内", class: "inputBox" %>
  </div>
  
  <div class="">
    <%= f.text_field :price, label: "値段", placeholder: "値段", class: "inputBox"  %>
  </div>
  
  <div class="">
    <%= f.text_field :kcal, label: "カロリー", placeholder: "カロリー", class: "inputBox"  %>
  </div>
  
  <div class="">
    <%= f.text_area :description, label: "内容", class: 'textBox',  placeholder: "200文字以内" %>
  </div>
  
  <div class="">
    <%= f.file_field :image %>
  </div>
  
  <div class = "button">
    <%= f.submit "登録", class: "btn" %>
  </div>
  
  
<% end %>

  

app/views/dashboard/menus/edit.html.erb
<section id="news" class="news">

  <h1>Edit Menu</h1>
  
  <%= render 'form', menu: @menu, url: dashboard_menu_path(@menu) %>
  <%= link_to 'Back', dashboard_menus_path %>

</section>

app/views/dashboard/menus/index.html.erb
<section class="menu" id="menu">
  <div class = "menus">
    
  <h1 class="heading"><span>Menu</span></h1>
    <%= link_to '+New Menu', new_dashboard_menu_path, class: "btn" %>
      
    <div class="box-container">
      <% @menus.each do |menu| %>
        <div class="box">
          <span class="price">￥<%= menu.price %></span>
          <% if menu.image.present? %>
            <%= image_tag menu.image.to_s %>
          <% else %>
            <%= image_tag "/images/s-img-1.jpg", alt: "" %>
          <% end %>
          <h3><%= menu.name %></h3>
          <h3><%= menu.kcal %><em>kcal</em></h3>
          <div>
            <%= link_to 'Edit', edit_dashboard_menu_path(menu), class: "btn" %>
            <%= link_to 'Destroy', dashboard_menu_path(menu), class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          
        </div>
      <% end %>
    </div>
    
  </div>
  
</section>

app/views/dashboard/menus/new.html.erb
<section id="news" class="news">

  <h1>New Menu</h1>
  
  <%= render 'form', menu: @menu, url: dashboard_menus_path %>
  <%= link_to 'Back', dashboard_menus_path %>

</section>