config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
   sessions: "admins/sessions"
  }

  devise_scope :admin do
    get "dashboard", to: "dashboard#index"
    get "dashboard/login", to: "admins/sessions#new"
    post "dashboard/login", to: "admins/sessions#create"
    delete "dashboard/logout", to: "admins/sessions#destroy"
  end
  namespace :dashboard do
    resources :posts
    resources :menus, except: [:show]
  end
  
  root to: "home#index"
  resources :posts, only: %i[index show]
  resources :contacts, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/dashboard/menus_controller.rb
class Dashboard::MenusController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_menu, only: %i[edit update destroy]
  
  def index
    @menus = Menu.all.order(id: "DESC")
  end
  
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to dashboard_menus_path, notice: 'menu was successfully created.'
    else
      render :new, notice: 'Save error.'
    end
  end
  
  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to dashboard_menus_path, notice: 'menu was successfully updated.'
    end
  end

  def destroy
    @menu.destroy
    redirect_to dashboard_menus_url, notice: 'menu was successfully destroyed.'
  end
  
   private
    def set_menu
      @menu = Menu.find(params[:id])
    end
    
    def menu_params
      params.require(:menu).permit(:name, :price, :description, :kcal, :image)
    end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  layout 'dashboard/dashboard'
  before_action :authenticate_admin!
  before_action :set_post, only: %i[show edit update destroy]
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def show
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to dashboard_posts_path, notice: 'Posts was successfully created.'
    end
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_posts_path, notice: 'Post was successfully updated.'
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_posts_url, notice: 'Post was successfully destroyed.'
  end
  
   private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def show
  end
  
   private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/dashboard/menus_helper.rb
module Dashboard::MenusHelper
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashboard/posts/_form.html.erb
<%= simple_form_for(post, url: url, local: true, action: :action) do |f| %>
  <%= f.error_notification %>

  <%= f.input :title, label: "タイトル", placeholder: "20文字以内" %>
  <%= f.input :content, as: :summernote, label: "内容",  placeholder: "200文字以内" %>
  <div class="button">
    <%=  f.submit "投稿へ", class: "btn", id: "btn_id" %>
  </div>
  
<% end %>

app/views/dashboard/posts/edit.html.erb
<section id="news" class="news">
  <h1>Editing Post</h1>
  
  <%= render 'form', post: @post, url: dashboard_post_path(@post) %>
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', dashboard_posts_path %>
</section>

app/views/dashboard/posts/index.html.erb
<section id="news" class="news">
  
  <h1 class="heading"><span></span>記事一覧</span></h1>
  <%= link_to '+New Post', new_dashboard_post_path, class: "btn" %>
  <div class = "box-container">
    <div class = "box">
      <% @posts.each do |post| %>
        <div class =  "content">
          <p><%= l post.created_at  %></p>
          <%= link_to post.title, dashboard_post_path(post), class: "post-title" %>
          <p class="post-cat"><span>#</span>お店の紹介</p>
          <p class="post-cat"><span>#</span>お店の紹介</p>
          
        
          <p><%=raw truncate(post.content.html_safe) %></p>
          <%= link_to "続きを読む", dashboard_post_path(post), class: "post-next" %>
          <div>
            <%= link_to 'Edit', edit_dashboard_post_path(post), class: "btn" %>
            <%= link_to 'Destroy', dashboard_post_path(post), class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          
        </div>
        
      <% end %>
    </div>
  </div>

    
  


</section>

app/views/dashboard/posts/new.html.erb
<section id="news" class="news">
  <h1>New Post</h1>
  
  <%= render 'form', post: @post, url: dashboard_posts_path %>
  <%= link_to 'Back', dashboard_posts_path %>
</section>

app/views/dashboard/posts/show.html.erb
<section id="news" class="news">
  
  <div class = "box-container">
    <div class = "box">
      <div class = "content show-content">
        <p><%= l @post.created_at %></p>
        <h3 class = "post-title"><%= @post.title%></h3>
        <p class="post-cat"><span>#</span>お店の紹介</p>
        <p class="post-cat"><span>#</span>お店の紹介</p>

        <p><%== @post.content %></p>
      </div>
    </div>
  </div>
  <%= link_to "⬅ 戻る", dashboard_posts_path %>
  
</section>