config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
   sessions: "admins/sessions"
  }

  devise_scope :admin do
    get "dashboard", to: "dashboard#index"
    get "dashboard/login", to: "admins/sessions#new"
    post "dashboard/login", to: "admins/sessions#create"
    delete "dashboard/logout", to: "admins/sessions#destroy"
  end
  namespace :dashboard do
    resources :posts
    resources :menus, except: [:show]
  end
  
  root to: "home#index"
  resources :posts, only: %i[index show]
  resources :contacts, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  enum answer_to_return: {"電話" => 0, "メール" => 1}
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 }, format: { with: VALID_EMAIL_REGEX }
  validates :subject,  presence: true, length: { maximum: 20 }
  validates :phone_numb,  presence: true, length: { maximum: 15 }
  validates :answer_to_return,  presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:new, :create, :destroy]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end
  
  def after_sign_in_path_for(user)
    dashboard_path
  end

  def after_sign_out_path_for(user)
    root_path
  end


  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(
      :sign_in, keys: [ :name, :email, :password, :password_confirmation ])
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to root_path, notice: '送信されました'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :phone_numb, :message, :answer_to_return)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @menus = Menu.all
    @answer = Contact.answer_to_returns
    @contact = Contact.new
  end
  
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to root_path, notice: '送信されました'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :phone_numb, :message, :answer_to_return)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def show
  end
  
   private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_is_user?
    request.fullpath == "/login"
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard/menus_helper.rb
module Dashboard::MenusHelper
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def restaurant_map
    iframe = content_tag(
      :iframe,
      '',
      height: '400',
      src: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.4466958110115!2d139.73464221478676!3d35.66600153841542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b835942e165%3A0xb4897f1f4264c771!2z44CSMTA2LTAwMzIg5p2x5Lqs6YO95riv5Yy65YWt5pys5pyo77yS5LiB55uu77yU4oiS77yV!5e0!3m2!1sja!2sjp!4v1543466837094",
      frameborder: 0,
      allowfullscreen: true
      )
      content_tag(:div, iframe)
  end
end

# width="800" height="400" frameborder="0" style="border:0"

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>

  <div class="share">
    <%= link_to 'home', root_path, class: "btn" %>
    <%= link_to 'news', posts_path, class: "btn" %>
    <%= link_to 'menu', '#menu', class: "btn" %>
    <%= link_to 'location', '#location', class: "btn" %>
    <%= link_to 'contact', '#contact', class: "btn" %>
  </div>

  <h1 class="credit"> created by <span> Hiroshi Hatazawa </span> | all rights reserved! </h1>

</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag "/images/logo.svg", class: "logo", alt: "WCBカフェ ホーム" %>
  <% end %>
  
  <div id = "menu-bar" class = "fas fa-bars"></div>
  
  <nav class = "navbar">
    <%= link_to 'home', root_path %>
    <%= link_to 'news', posts_path %>
    <%= link_to 'menu', '#menu' %>
    <%= link_to 'location', '#location' %>
    <%= link_to 'contact', '#contact' %>
  </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name = 'viewport' content = 'width=device-width, initial-scale=1'>
    <title>WCB CAFE</title>
    <meta name = 'description' content = 'ブレンドコーヒートヘルシーなオーガニックフードを提供するカフェ'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://kit.fontawesome.com/8c770f7830.js' crossorigin='anonymous'></script>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    
    <%= yield %>
    
    <%= render partial: 'layouts/footer' %>
    <%= link_to '', "#home", class: "fas fa-angle-up", id: "scroll-top" %>
  </body>
</html>